//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tickMeter.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("tickMeter.Resources.en", typeof(en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Low data color.
        /// </summary>
        internal static string ColorBad {
            get {
                return ResourceManager.GetString("ColorBad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Good quality data color.
        /// </summary>
        internal static string ColorGood {
            get {
                return ResourceManager.GetString("ColorGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Overlay Labels Color.
        /// </summary>
        internal static string ColorLabel {
            get {
                return ResourceManager.GetString("ColorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hormal color.
        /// </summary>
        internal static string ColorMid {
            get {
                return ResourceManager.GetString("ColorMid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Network connection:.
        /// </summary>
        internal static string network_connection_lbl {
            get {
                return ResourceManager.GetString("network_connection_lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Possible Risks.
        /// </summary>
        internal static string possible_risks_lbl {
            get {
                return ResourceManager.GetString("possible_risks_lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Remember.
        /// </summary>
        internal static string rememberAdapter {
            get {
                return ResourceManager.GetString("rememberAdapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        internal static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tickrate graph.
        /// </summary>
        internal static string settings_chart_checkbox {
            get {
                return ResourceManager.GetString("settings_chart_checkbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Display IP.
        /// </summary>
        internal static string settings_ip_checkbox {
            get {
                return ResourceManager.GetString("settings_ip_checkbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Log tickrate to CSV.
        /// </summary>
        internal static string settings_log_checkobx {
            get {
                return ResourceManager.GetString("settings_log_checkobx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Disable network analyze
        ///(if tickMeter crashes).
        /// </summary>
        internal static string settings_netstats_checkbox {
            get {
                return ResourceManager.GetString("settings_netstats_checkbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Display Ping and country.
        /// </summary>
        internal static string settings_ping_checkbox {
            get {
                return ResourceManager.GetString("settings_ping_checkbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Use RTSS output overlay.
        /// </summary>
        internal static string settings_rtss_output {
            get {
                return ResourceManager.GetString("settings_rtss_output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Display connection time.
        /// </summary>
        internal static string settings_session_time_checkbox {
            get {
                return ResourceManager.GetString("settings_session_time_checkbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Display traffic.
        /// </summary>
        internal static string settings_traffic_checkbox {
            get {
                return ResourceManager.GetString("settings_traffic_checkbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Update Available .
        /// </summary>
        internal static string updateLbl {
            get {
                return ResourceManager.GetString("updateLbl", resourceCulture);
            }
        }
    }
}
