//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tickMeter.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("tickMeter.Resources.en", typeof(en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network connection:.
        /// </summary>
        internal static string network_connection_lbl {
            get {
                return ResourceManager.GetString("network_connection_lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tickrate graph.
        /// </summary>
        internal static string settings_chart_checkbox {
            get {
                return ResourceManager.GetString("settings_chart_checkbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display IP.
        /// </summary>
        internal static string settings_ip_checkbox {
            get {
                return ResourceManager.GetString("settings_ip_checkbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string settings_lbl {
            get {
                return ResourceManager.GetString("settings_lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log tickrate to CSV.
        /// </summary>
        internal static string settings_log_checkobx {
            get {
                return ResourceManager.GetString("settings_log_checkobx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Ping and country.
        /// </summary>
        internal static string settings_ping_checkbox {
            get {
                return ResourceManager.GetString("settings_ping_checkbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use RTSS output overlay.
        /// </summary>
        internal static string settings_rtss_output {
            get {
                return ResourceManager.GetString("settings_rtss_output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display traffic.
        /// </summary>
        internal static string settings_traffic_checkbox {
            get {
                return ResourceManager.GetString("settings_traffic_checkbox", resourceCulture);
            }
        }
    }
}
